// interaction sweep for the systems added since v80: clicks through dialogue cards, the Bag, the prize counter, designs, photos,
// fishing, neighbours' chats and conversations, and checks that every choice button is actually visible (opacity, size, on screen).
// Run before each release with sweep.js and sweep2.js:  node tools/dev/town/run.js tools/dev/town/sweep3.js
module.exports=async({ev,pg,wait,log})=>{const errs=[];pg.on('pageerror',e=>errs.push('pageerror: '+e.message));
 for(let i=0;i<120;i++){if(await ev('ready&&!ARR.on')==='true')break;await wait(1000)}await wait(1000);
 const R=async(name,code)=>{const r=await ev(code);if(typeof r==='string'&&r.startsWith('ERR'))errs.push(name+': '+r.split('\n').slice(0,3).join(' | '));else if(typeof r==='string'&&/INVISIBLE|MISSING/.test(r))errs.push(name+': '+r);return r};
 await ev(`window.__vis=sel=>{const B=[...document.querySelectorAll(sel)];B.forEach(b=>{try{b.getAnimations().forEach(a=>a.finish())}catch(_){}});if(!B.length)return'MISSING '+sel;const bad=B.filter(b=>{const cs=getComputedStyle(b),r=b.getBoundingClientRect();let op=1;for(let e=b;e;e=e.parentElement)op*=+getComputedStyle(e).opacity;return op<.3||cs.visibility==='hidden'||r.width<8||r.height<8});return bad.length?'INVISIBLE '+bad.length+'/'+B.length+' '+sel+' '+(()=>{const b=bad[0],r=b.getBoundingClientRect();let op=1;for(let e=b;e;e=e.parentElement)op*=+getComputedStyle(e).opacity;return Math.round(r.width)+'x'+Math.round(r.height)+' op'+op.toFixed(2)+' '+getComputedStyle(b).visibility})():'ok '+B.length};
   localStorage.setItem('r42locAsked','1');rewardQ.length=0;$('#reward').hidden=true;state.btn=5000;state.tix=3000;state.glim=50;1`);
 const close="(()=>{const d=$('#dlyBox');if(d)d.hidden=true;rewardQ.length=0;$('#reward').hidden=true;closeProduct();return 1})()";
 // dialogue cards and their choices
 await R('basket',`(()=>{(state.acts||{})[dKey('basket')]=null;dlyBasket();return __vis('#dlyBox .cvline')})()`);await ev(close);
 await R('well',`(()=>{(state.acts||{})[dKey('well')]=null;dlyWell();const v=__vis('#dlyBox .cvch button');document.querySelector('#dlyBox [data-dc="0"]').click();return v})()`);await ev(close);
 await R('joke',`(()=>{(state.acts||{})[dKey('joke')]=null;dlyJoke(false);const v1=__vis('#dlyBox .cvch button');document.querySelector('#dlyBox [data-dc="0"]').click();const v2=__vis('#dlyBox .cvch button');document.querySelector('#dlyBox [data-dc="0"]').click();const v3=__vis('#dlyBox .cvch button');return [v1,v2,v3].join(' / ')})()`);await ev(close);
 await R('mystery',`(()=>{(state.acts||{})[dKey('mystery')]=null;dlyMystery();const v=__vis('#dlyBox .cvch button');document.querySelector('#dlyBox [data-dc="1"]').click();return v})()`);await ev(close);
 await R('mayor',`(()=>{state.mayorM='2000-01';dlyMayorTick();return state.mayorM})()`);await ev(close);
 await R('wellTick',`(()=>{const k=dKey('well');state.acts[k]={d:'2000-01-01',k:'cozy'};dlyWellTick();return state.acts[k].g})()`);
 // the Bag: every tab, every action on a treasure and a food
 for(const t of ['food','groom','toy','treasure','keep','furn','wear','seed']){await ev(`bagTab='${t}';setTab('bag');1`);for(let i=0;i<40;i++){if(await ev("!$('#sheet').classList.contains('gen')")===true)break;await wait(300)}await wait(300);await R('bag '+t,`__vis('.bagtabs .chip')`)}
 await R('bag actions',`(()=>{['t_scallop','t_spiral','t_pearl','t_conch'].forEach(id=>treasureGet(id,true));const o=[];for(const a of ['sell','disp','give']){bagOpen(a==='sell'?'t_scallop':a==='disp'?'t_pearl':'t_spiral');const b=document.querySelector('#shopcard [data-ba='+a+']');if(!b)return'MISSING '+a;b.click();if(a==='give'){const g=document.querySelector('[data-gk]');if(!g)return'MISSING give list';g.click()}}return o.join(',')})()`);await ev(close);
 await ev(`state.inv.cookie=2;bagOpen('cookie');1`);await wait(2500);await R('bag food',`__vis('#shopcard [data-ba]')`);await ev(close);
 // the prize counter: buy something of each kind
 await ev(`setTab('prizes');1`);await wait(900);await R('prizes',`(()=>{const L=prizeList(),o=[];['furn','toy','food','prize','glim'].forEach(t=>{const i=L.findIndex(p=>p.t===t&&!(p.t==='toy'&&p.own));if(i<0)return;document.querySelectorAll('[data-pz]')[i].click();o.push(t)});return o.join(',')+' '+__vis('[data-pz]')})()`);
 // designs: make, edit, frame, delete
 await R('designs',`(()=>{setTab('decorate');decoView='design';renderSheet();dzOpen(null);const v='';dz.px.fill(3);$('#dzSave').click();const D=state.designs[0];dzCard(D.id);document.querySelector('#shopcard [data-a=frame]').click();dzOpen(D.id);dz.px[0]=5;$('#dzSave').click();const N=state.designs[0];dzCard(N.id);const del=document.querySelector('#shopcard [data-a=del]');del.click();del.click();return v+' '+(state.designs.some(d=>d.id===N.id)?'NOT DELETED':'deleted')})()`);await ev(close+";setTab(null)");
 // photo: open, pose, shoot, album, close
 await R('photo',`(async()=>{phOpen();const v=__vis('#photo .phrow button');phPose();phShoot();await new Promise(r=>setTimeout(r,1500));await phAlbum();const a=__vis('#phAlbum .phx');$('#phAlbum').hidden=true;phClose();return v+' '+a})()`);
 // pet touch, rub, hold, arrival, mood
 await R('pet',`(()=>{petTouch(0);petTouch(1);petTouch(-1);for(let i=0;i<4;i++)petTouch(0);petRub(200,0);const ok=petPickUp();if(ok){petHoldMove(200,400);petDrop()}arrStart(Date.now()-5*36e5);arrEnd();petMood();return 'ok'})()`);
 await ev("setTab('scrap');1");await wait(2500);await R('scrap',`__vis('.jrtabs .chip')`);await ev("setTab(null);1");
 // the map: neighbours' chats, conversations (clicking through every top choice), fishing
 await ev("showMap();1");for(let i=0;i<60;i++){if(await ev("tm.pending")==='false')break;await wait(1000)}await wait(1500);
 await R('listen/join',`(()=>{rewardQ.length=0;$('#reward').hidden=true;tm.open=false;dbgAllHome=true;skyHourOverride=12;twResSync();const ks=[...tw.res.keys()],a=tw.res.get(ks[0]),b=tw.res.get(ks[1]),p=tw.pet,o=[];
   for(const join of [false,true]){[a,b].forEach((r,i)=>{r.x=p.x+1.5+i*.6;r.z=p.z+.3;r.path=null;r.plan={mode:'stroll',near:'home'};r.cool=0;r.chat=null;r.out=0;r.gone=0;r.sc=1});tw.rcPairT={};for(let i=0;i<3;i++){twTick(.05,tm.t+=.05);tmFrame(.05)}
     let n=rcNear(4.2);if(!n){for(let t=2;t<ks.length&&!n;t+=2){const c=tw.res.get(ks[t]),d=tw.res.get(ks[t+1]);if(!c||!d)break;[a,b].forEach(r=>{r.x=999;r.chat=null});[c,d].forEach((r,i)=>{r.x=p.x+1.5+i*.6;r.z=p.z+.3;r.path=null;r.plan={mode:'stroll',near:'home'};r.cool=0;r.chat=null;r.out=0;r.gone=0;r.sc=1});tw.rcPairT={};for(let i=0;i<3;i++){twTick(.05,tm.t+=.05);tmFrame(.05)}n=rcNear(4.2)}}if(!n)return'MISSING chat '+JSON.stringify({res:tw.res.size,ks:ks.slice(0,4),ach:a.chat&&{w:a.chat.w,f:a.chat.first,sc:!!a.chat.sc,sn:a.chat.sc&&a.chat.sc.snub},d:Math.hypot(a.x-b.x,a.z-b.z),rc:!!rc,cv:!!cv,card:!$('#tmCard').hidden,pmode:a.plan&&a.plan.mode});rcOpen(n,join);let g=0;while(rc&&g++<20){rc.shown=rc.full.length;rcType(0);const v=__vis('#tmCard .cvline');if(v.startsWith('INV'))return v;const btn=document.querySelector('#cvCh:not([hidden]) button')||[...document.querySelectorAll('#tmCard .cvch button')].pop()||null;if(btn)btn.click();else document.querySelector('#tmCard').click()}if(rc)return'STUCK in chat after '+g;o.push((join?'join':'listen')+' '+g)}
   if(rc)rcEnd();$('#tmCard').hidden=true;skyHourOverride=null;return o.join(',')})()`);
 await R('conversations',`(()=>{const ks=['baker','cactus','makeup','book','pebble','cloud'],o=[];for(const k of ks){if(!tw.res.get(k))continue;cvBegin(k);let g=0;while(cv&&g++<12){cv.shown=cv.full.length;cvType(0);const v=__vis('#cvCh button');if(v.startsWith('INV')||v.startsWith('MISS'))return k+' '+v;const B=[...document.querySelectorAll('#cvCh button')];const b=B[Math.floor(Math.random()*B.length)];if(/gift/i.test(b.textContent)){B[B.length-1].click()}else b.click()}if(cv)cvEnd();o.push(k+':'+g)}return o.join(' ')})()`);
 await R('fishing',`(()=>{rewardQ.length=0;FI=null;fishStart('sea');FI.F=fishRoll('sea');FI.ph='bite';FI.t=0;fishTap();const v=__vis('#dlyBox .cvch button');document.querySelector('#dlyBox [data-dc="1"]').click();return v+' '+Object.keys(state.fbest||{}).length})()`);await ev(close);
 await R('season',`(()=>{for(const S of ['spring','summer','autumn','winter']){dbgSeason=S;tm.seaDecorS=null;tmSeasonDecor();tm.mergeDirty=true;tmFrame(.05)}dbgSeason=null;return 'ok'})()`);
 log('sweep3 done, errors '+errs.length);errs.slice(0,30).forEach(e=>log(e))};
